= HA/DR Architect Enablement

== Our Story (Current & Future)

The Entire OpenShift and Kubernetes space is trending towards a world where we treat clusters as cattle. To that, we need to be training our customers to build towards production solutions that involve multiple clusters, and the ability to easily fail over between them.

* Multiple clusters
  ** Fully automated using Infrastructure as Code (CASL, OpenShift Applier)
* Load balanced locally with an Local Traffic Managers (Reverse Proxy)
* Load balanced Globally through Global Traffic Managers (DNS)
* Externalized state & storage
  ** CRS
  ** Cloud Provider Native storage
* Roadmap

== CASL & Applier

=== CASL Becoming More Consultant Friendly
https://github.com/redhat-cop/casl-ansible/pull/237
https://github.com/etsauer/casl-ansible/tree/docs-host-prep

=== LEARN APPLIER
https://github.com/redhat-cop/openshift-applier
http://v1.uncontained.io/playbooks/fundamentals/template_development_guide.html

== LTM & GTM

Whiteboarding Session

== External Storage Architectures

Whiteboarding Session & Open Discussion

== Roadmap Discussion

Will discuss some product features that are coming that may help with this story.

== What we need to do

- Research & Develop Smarter Global Load Balancing Strategies
- A reference implementation of CNS & CRS architectures
